### ISSUE TITLE
Missing Semicolon on line bind9_enable_ipv6 in the named.conf.local template

### ISSUE THREAD

**Issue by shawntackaberry** [ricsanfre/ansible-role-bind9#2]
When enabling bind9_enable_ipv6 and not specifying any IP's the any option does populate however there is no semicolon added to the generated file.

I added one in my own instance and it seemed to rectify the issue.

Original: listen-on-v6 { {% if bind9_listen_on_v6|default() %}{% for ip in bind9_listen_on_v6 %}{{ ip }};{% endfor %}{% else %}any{% endif %} };
Updated:  listen-on-v6 { {% if bind9_listen_on_v6|default() %}{% for ip in bind9_listen_on_v6 %}{{ ip }};{% endfor %}{% else %}any{% endif %}; };

**Comment by ricsanfre** [comment]
Thanks for your highlighting this issue @shawntackaberry

**Comment by ricsanfre** [comment]
Fix by d3c216f
